### PR TITLE
Fixed a few grammar issues in the README.md

### PR DESCRIPTION
**Pull request by yotixify**
Definitely interested in this project more, and will look into it! Great idea!

### CODE REVIEW

**Comment by paulirish** [comment]
probably redundant due to #2

**Comment by yotixify** [comment]
I saw the changes https://github.com/kjepper/CallerPi/pull/2 made, I caught a couple things he didnt get. If you don't want to merge it no worries. You might want to add ` ticks for the code as well to make the markdown look a little nicer

**Comment by paulirish** [comment]
i'm just another redditor, not the repo owner. ;)

your "install" fix conflicts with the PR in #2, which is why i commented.
looks like he's already indenting and fencing for code: https://github.com/devoxel/CallerPi/blob/master/README.md <= preview

**Comment by yotixify** [comment]
Hah, true that, didnt see that earlier...but then again was reviewing it on my phone before I jumped on my laptop and made the changes. I can close this Pull Request.

**Pull request closed without merging**
